name = "subscouter"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "subscouter-db"
database_id = "64726430-85a0-4a89-9337-b2b2dcfab1d2"

# R2 Bucket Binding
[[r2_buckets]]
binding = "STORAGE"
bucket_name = "subscouter-storage"

[vars]
# STRIPE_WEBHOOK_SECRET should be set via 'wrangler secret put'
# STRIPE_WEBHOOK_SECRET = "sk_..." 
